# Generated by Django 2.0.2 on 2018-03-02 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['first_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='competition',
            options={'ordering': ['competition_name']},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['grade_name']},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['language_name']},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'ordering': ['university_name']},
        ),
        migrations.RemoveField(
            model_name='grade',
            name='entrance_year',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='graduate_year',
        ),
        migrations.AddField(
            model_name='mentor',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.University'),
        ),
    ]
