# Generated by Django 2.0.2 on 2018-03-02 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import register.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_auto_20180302_0342'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_fname', models.CharField(blank=True, max_length=200)),
                ('user_lname', models.CharField(blank=True, max_length=200)),
                ('is_head', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('skills', models.TextField(blank=True)),
                ('entrance_year', models.IntegerField(blank=True, default=1396)),
                ('graduate_year', models.IntegerField(blank=True, default=1400)),
                ('grade', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Grade')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=3)),
                ('code_address', models.TextField(blank=True, default='')),
                ('win', models.IntegerField(default=0)),
                ('loose', models.IntegerField(default=0)),
                ('draw', models.IntegerField(default=0)),
                ('logo_image', models.ImageField(default='unknown.jpg', height_field='height_field', null=True, upload_to=register.models.upload_location, width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('team_bio', models.TextField(blank=True, default='')),
                ('mentor', models.CharField(blank=True, default='', max_length=20)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Competition')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Language')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.University')),
                ('user_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='/home/Armankadeh/ArmanRayan_Jam/statics/img/unknown.jpg', height_field='height_field', null=True, upload_to=register.models.upload_test, width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='myuser',
            name='team',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Users', to='register.Team'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='university',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.University'),
        ),
    ]
